data:
  data_dir: "./dataset"
  processed_dir: "./processed_data"
  common_settings:
    resize: [224, 224] # Standard size for all datasets
    channels: 3 # Enforce RGB
    pad_to_square: true
    normalize: true
    normalization:
      mean: [0.485, 0.456, 0.406] # ImageNet stats as default
      std: [0.229, 0.224, 0.225]

  dataset_structure:
    standard: # datasets with train/val/test
      - chest_xray
      - rotc
    train_test: # datasets with only train/test
      - dermnet
      - scisic
    train_valid_test: # datasets with train/valid/test
      - ccts
    class_based: # datasets with class folders
      - tbcr
    object_detection: # datasets with separate image and annotation folders
      - cattleface
    metadata_format:
      tbcr:
        - "Normal.metadata.xlsx"
        - "Tuberculosis.metadata.xlsx"

  data_key:
    - name: scisic
      modality: dermoscopy
      train_dir: "scisic/Train"
      test_dir: "scisic/Test"
      normalization:
        mean: [0.7437659, 0.58653116, 0.58686644]
        std: [0.08040085, 0.10757149, 0.12017569]
      augmentation:
        contrast_enhancement: true
        brightness_adjustment: false
      class_balancing: weighted_loss # Added due to severe class imbalance (ratio: 6.00)
      duplicate_removal: true
      structure:
        type: "train_test"
        train: "Train"
        test: "Test"
        split_ratios: [0.85, 0.15] # train/val from train set
      training:
        epochs: 5
        batch_size: 32
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      padding:
        enabled: true
        strategy: "symmetric" # For handling varying dimensions

    - name: ccts
      modality: ct
      train_dir: "ccts/train"
      test_dir: "ccts/test"
      normalization:
        mean: [0.323004, 0.32297248, 0.32300267]
        std: [0.22162104, 0.22161943, 0.2216194]
      conversion: convert_to_3_channel # Important - handles multiple channel types
      duplicate_removal: true
      structure:
        train: "train"
        valid: "valid"
        test: "test"
        type: "train_valid_test"
      class_normalization:
        # Define rules for normalizing class names
        patterns:
          # Pattern-based replacement (regex)
          "^(adenocarcinoma).*": "adenocarcinoma"
          "^(large\\.cell\\.carcinoma).*": "large.cell.carcinoma"
          "^(squamous\\.cell\\.carcinoma).*": "squamous.cell.carcinoma"
        # Optional direct mappings for specific cases
        mapping:
          "adenocarcinoma_left.lower.lobe_T2_N0_M0_Ib": "adenocarcinoma"
          "large.cell.carcinoma_left.hilum_T2_N2_M0_IIIa": "large.cell.carcinoma"
          "squamous.cell.carcinoma_left.hilum_T1_N2_M0_IIIa": "squamous.cell.carcinoma"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.0001
        momentum: 0.9
        weight_decay: 1e-4
      augmentation:
        contrast_enhancement: false # Contrast levels are acceptable
      padding:
        enabled: true
        strategy: "symmetric"

    - name: rotc
      modality: oct
      train_dir: "rotc/train"
      test_dir: "rotc/test"
      normalization:
        mean: [0.19338988, 0.19338988, 0.19338988]
        std: [0.1933612, 0.1933612, 0.1933612]
      conversion: convert_to_3_channel # Change to handle grayscale images
      duplicate_removal: true
      structure:
        train: "train"
        val: "val"
        test: "test"
      training:
        epochs: 100
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      augmentation:
        brightness_adjustment: true # Added due to low brightness
      preprocessing:
        clahe: true # For contrast enhancement
      padding:
        enabled: true
        mode: "constant"
        value: 0

    - name: kvasir
      modality: endoscopy
      train_dir: "kvasir/train"
      normalization:
        mean: [0.48510954, 0.34737176, 0.30044696]
        std: [0.29461348, 0.22394758, 0.19942161]
      duplicate_removal: true
      structure:
        train: "train"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      padding:
        enabled: true
        strategy: "symmetric" # For handling varying dimensions
      augmentation:
        contrast_enhancement: false # Contrast is acceptable

    - name: dermnet
      modality: dermoscopy
      train_dir: "dermnet/train"
      test_dir: "dermnet/test"
      normalization:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      duplicate_removal: true
      structure:
        train: "train"
        test: "test"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4

    - name: chest_xray
      modality: xray
      train_dir: "chest_xray/train"
      test_dir: "chest_xray/test"
      normalization:
        mean: [0.48230693, 0.48230693, 0.48230693]
        std: [0.22157896, 0.22157896, 0.22157896]
      conversion: convert_to_3_channel # Handle both grayscale and RGB
      duplicate_removal: true
      structure:
        train: "train"
        val: "val"
        test: "test"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
      padding:
        enabled: true
        strategy: "symmetric" # For varying dimensions
      preprocessing:
        remove_noise: true # Add noise reduction

    - name: tbcr
      modality: ct
      train_dir: "tbcr"
      normalization:
        mean: [0.5013298, 0.5097307, 0.5125384]
        std: [0.23488876, 0.23702013, 0.2381724]
      conversion: convert_to_3_channel
      duplicate_removal: true
      structure:
        type: "class_based"
        classes:
          - "Normal"
          - "Tuberculosis"
        metadata_files:
          - "Normal.metadata.xlsx"
          - "Tuberculosis.metadata.xlsx"
        split_ratios: [0.7, 0.15, 0.15]
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4

    - name: miccai_brats2020
      modality: mri
      train_dir: "miccai_brats2020/MICCAI_BraTS2020_TrainingData"
      normalization:
        mean: [0.5, 0.5, 0.5]
        std: [0.25, 0.25, 0.25]
      conversion: none
      duplicate_removal: true
      structure:
        train: "MICCAI_BraTS2020_TrainingData"
      training:
        epochs: 30
        batch_size: 64
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4

    - name: cattleface
      modality: object_detection
      train_dir: "cattleface"
      images_dir: "CowfaceImage"
      annotations_dir: "Annotation"
      normalization:
        mean: [0.36444724, 0.34213632, 0.33240524]
        std: [0.23644538, 0.24627125, 0.2506246]
      duplicate_removal: true # No duplicates found
      structure:
        type: "object_detection"
        images: "CowfaceImage"
        annotations: "Annotation"
        annotation_format: "yolo" # Based on .txt files
      training:
        epochs: 50
        batch_size: 16
        lr: 0.001
        momentum: 0.9
        weight_decay: 1e-4
        imgsz: 640
        data: "./cattleface.yaml" # Path to YOLO dataset config (must exist and be correct)
      class_balancing: weighted_loss
      image_properties:
        consistent_dimensions: true
        size: [2560, 1440]
        channels: 3
        orientation: "landscape"
        color_space: "RGB"
      quality_assessment:
        corrupted_files: false
        sharpness_level: "acceptable" # Laplacian variance: 1685.32
        brightness: 86.71
        contrast: 69.27
        noise_level: "low"
      augmentation:
        data_augmentation: true # Recommended due to limited variation
        brightness_adjustment: true # Limited brightness range: 16.59
        contrast_enhancement: true # Limited contrast range: 11.02
        geometric_transforms: true
      preprocessing:
        resize_needed: true # Consistent dimensions
        normalization_needed: false # Pixel values already in [0,1] range
      validation:
        split_ratio: 0.2 # Create validation set from training data
        stratified: true # Maintain class distribution
        stratified: true # Maintain class distribution
